### ISSUE TITLE
Expand opportunities of RESTful API

### ISSUE THREAD

**Issue by osminogin** [openbeer/docs#1]
I'm trying to write example Angular2 application that interacts with the existing available OpenBeer API. 

In my opinion API is incomplete and difficult to use (probably not even possible as external REST service). You can get some of the key elements is not possible to get a list of entities . 

I'm need some method to get a list of keys, for example, `GET /beer/` returns a list of keys, possibly with restrictions or pagination.

**Comment by geraldb** [comment]
@osminogin  Thanks for your interest in beer.db. Please send questions and comments to the [forum / mailing list](http://groups.google.com/group/beerdb). Cheers.
