### ISSUE TITLE
a bit more functionalities :)

### ISSUE THREAD

**Issue by moebiusmania** [openbeer/docs#2]
hi, and great job with the openbeer.db!
I was playing a bit with your JSON API and all seems fine, but I think it would be useful to have a bit more functionalities, just as musch as needed to replicate your [admin application](http://prost.herokuapp.com/it) (list all beers by country)

You think it is possible? and what kind of help could you need?

**Comment by geraldb** [comment]
Yes, it is possible. You're more than welcome. It's DIY (do-it-yourself) ;-)   Please feel free to (re)use as much code as you need from the admin app. Please post question and comments to the [forum / mailinglist](http://groups.google.com/group/beerdb). Cheers.
